# ----------------- Auth Service -----------------
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: bloghive
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: bloghive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: 457795063740.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest
          ports:
            - containerPort: 9000
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            # --- Retry settings ---
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
            - name: SPRING_CLOUD_CONFIG_RETRY_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS
              value: "30"
            - name: SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL
              value: "3000"
            - name: EUREKA_CLIENT_RETRY_ENABLED
              value: "true"

---
# ----------------- Post Service -----------------
apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: bloghive
spec:
  selector:
    app: post-service
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service-deployment
  namespace: bloghive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: 457795063740.dkr.ecr.us-east-1.amazonaws.com/post-service:latest
          ports:
            - containerPort: 9001
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            # --- Retry settings ---
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
            - name: SPRING_CLOUD_CONFIG_RETRY_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS
              value: "30"
            - name: SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL
              value: "3000"
            - name: EUREKA_CLIENT_RETRY_ENABLED
              value: "true"

---
# ----------------- Comment Service -----------------
apiVersion: v1
kind: Service
metadata:
  name: comment-service
  namespace: bloghive
spec:
  selector:
    app: comment-service
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service-deployment
  namespace: bloghive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - name: comment-service
          image: 457795063740.dkr.ecr.us-east-1.amazonaws.com/comment-service:latest
          ports:
            - containerPort: 9002
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            # --- Retry settings ---
            - name: SPRING_CLOUD_CONFIG_FAIL_FAST
              value: "false"
            - name: SPRING_CLOUD_CONFIG_RETRY_ENABLED
              value: "true"
            - name: SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS
              value: "30"
            - name: SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL
              value: "3000"
            - name: EUREKA_CLIENT_RETRY_ENABLED
              value: "true"